
name: Deploy to ping.pub

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ master ]

jobs:
  deploy:
    name: Ping deploy
    runs-on: mainnet 
    steps:
    - name: Environment
      run:  export NODE_OPTIONS="--max_old_space_size=4096"
         
    - name: Clean Repository
      run: rm -rf explorer
     
    - name: Git Checkout Latest
      uses: actions/checkout@v4   
      with:
        submodules: recursive

    - name: Setup config
      run: cp -rf chains/* explorer/chains/

    - name: Build
      run: cd explorer && yarn && yarn build
      
    - name: copy logos
      run: cp -rf logos explorer/dist/
      
    # - name: debug  
    #   run: ls -l explorer/dist/logos
      
    - name: Deploy
      run: cp -rf explorer/dist/* /var/www/html/
